### ISSUE TITLE
Unable to install via node, OSX

### ISSUE THREAD

**Issue by blasetheodore** [malcolmocean/wf2roam#1]
OSX.
NPM installed via Brew.

`npm install --save wf2roam`
 results in:

```
npm WARN notsup Unsupported engine for wf2roam@0.1.1: wanted: {"node":"10.14.2"} (current: {"node":"14.2.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: wf2roam@0.1.1
```

Is this user error or is something not right? Thanks!

**Comment by malcolmocean** [comment]
Ahh oops, I set it to only work with a specific version of node. Just shipped 0.1.2 which works with all versions of now newer than 10.14.2, instead of only 10.14.2.
